# Generated by Django 5.1 on 2024-08-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marks',
            options={'verbose_name': 'Mark', 'verbose_name_plural': 'Baholar/Izohlar'},
        ),
        migrations.AlterField(
            model_name='sellers',
            name='code',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
