# Generated by Django 5.1 on 2024-09-11 11:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_category_marks_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=221, verbose_name='FILIAL NOMI'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=221, verbose_name='KATEGORIYA NOMI'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.category', verbose_name='KATEGORIYA NOMI'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='YARATILGAN VAQT'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='IZOH'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='mark',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='BAHO'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.sellers', verbose_name='SAVDOGAR'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.user', verbose_name='BAHO BERGAN SHAXS'),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.branch', verbose_name='FILIAL'),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='code',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='MAXSUS KOD'),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='first_name',
            field=models.CharField(blank=True, max_length=221, null=True, verbose_name='ISM'),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='last_name',
            field=models.CharField(blank=True, max_length=221, null=True, verbose_name='FAMILIYA'),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='TELEFON RAQAM'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=221, null=True, verbose_name='F.I.Sh'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='TELEFON RAQAM'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(unique=True, verbose_name='TELEGRAM ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=221, null=True, verbose_name='USERNAME'),
        ),
    ]
